[package]
name = "harvester"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
oai-pmh = "0.1.0"
reqwest = "0.12.26"
tokio = { version = "1.48.0", features = ["full"] }
