---
services:
  db:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - path: .env
      - path: .env.local
        required: false
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

  dbadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    env_file:
      - path: .env
      - path: .env.local
        required: false
    user: $UID:$GID
    depends_on:
      - db
    volumes:
      - ${PWD}/dbadmin-data/:/var/lib/pgadmin/
